personalrobotics/chimera

CMakeLists.txt, external/cling/src/cling_utils_AST.cpp, src/chimera.cpp
These changes were necessary to get Chimera to build against Clang 4.0.0 on macOS. I believe this should: (1) not break backwards compatibility with Clang 3.6 and (2) should add support for the intermediate versions (i.e. 3.7, 3.8, and 3.9).
This may require some back-and-forth with Travis to make sure that it works on all those versions.
=> Support for Clang 3.8 and above

README.md
Now we can install Chimera using Homebrew. I've created a homebrew tap for PRL and added Chimera (and Aikido) formula there.
This PR adds a simple instruction of installing Chimera using Homebrew.
The current formula installs Chimera up to [this](https://github.com/personalrobotics/chimera/commits/4199c955c2145e83ccb622f07562c68d231091be) commit. The formula will be updated once we release Chimera with a tag.
=> Add instruction of installation using Homebrew

CMakeLists.txt, external/CMakeLists.txt, external/cling/CMakeLists.txt
Previously, mstch was built in-source using an `add_subdirectory()` directive.  This caused its `EXPORT` and `INSTALL` directives to be forwarded into chimera's own install step.
This PR changes the build process to use an `ExternalProject` to generate the static `mstch` library, which prevents this forwarding.
Closes #129.
=> Converts mstch build to an ExternalProject.

README.md
I moved the description from the Wiki to the `README`. This fixes #118.
=> Add note about key length to README

CMakeLists.txt, external/cling/CMakeLists.txt, test/CMakeLists.txt
This PR updates the CMakeLists.txt to use newer `target_` directives for includes and compile options, which removes some of the cruft associated with inheriting these properties.
The required version of CMake has been updated to 2.8.12 to make use of these newer features. This should be available on all targeted platforms (and specifically, Ubuntu 14.04).
Closes #141
=> Modified CMake to use newer directives.

README.md
This PR change the badge link to `travis.org` as Chimera became a public repository.
=> Change to travis.org

src/configuration.cpp
This commit fixes a typo in tag specification that was preventing correct parsing of the `!file` tag type to allow file paths to be specified as values in certain values in the configuration YAML.
=> Fixed a typo preventing file source loading.

.travis.yml, ci/install_macos.sh
The homebrew package name of llvm-4.0 was changed from `llvm@4.0` to `llvm@4` for some reason. This PR adjusts the llvm version inference logic in `install_macos.sh` accordingly.
Resolves #162
=> Fix build error on macOS + llvm-4.0

src/configuration.cpp
The `chimera::CompiledConfiguration::Lookup()` function is intended to handle either scalar values or (when a `file` tag is specified) a path to a file on disk.
This commit throws an error when neither of those two values is found in the node provided to `Lookup()`, instead of the previous behavior of simply returning an empty string instead.
This prevents configuration parsing issues from being masked by other errors due to the empty string.
Closes #160
=> Add error message when expected scalar is not found.

include/chimera/configuration.h, src/chimera.cpp, src/configuration.cpp
This addresses #165 where parent namespace declarations were being provided to the binding template
from `CompiledConfiguration` in an order that could not be used to construct namespace templates hierarchically (children were sometimes traversed before parents).
The underlying problem was that although the `ASTConsumer` guaranteed a hierarchical traversal of the `NamespaceDecls`, the traversed namespaces were being stored in a `std::set`, which re-ordered them arbitrarily by their canonical decl pointers.  This PR adds a `std::vector` which preserves the order of the namespaces for rendering, while still checking them against a `std::set` for de-duplication.
----
Closes #165
=> Added ordering to traversed namespaces in configuration.

ci/script.sh, external/cling/include/cling_utils_AST.h, external/cling/src/cling_utils_AST.cpp
chimera cannot be built with LLVM 6 because the disabled functions use private members of LLVM 6 (they used to be public in older versions). It seems those functions are not used in chimera anyway.
Resolves #172
=> Disable cling_utils_AST.h functions that are incompatible with LLVM 6

src/util.cpp
Previously, `template` must contain both of `file` and `main` items. Otherwise, it causes a runtime error.
This PR relaxes the requirements so that we only overwrite what we want.
Alternatively, we could check the validity of the node before calling `extendWithYAMLNode()`, but I chose this way because it seems this function has another validity check (whether the node is a map) inside already.
=> Make file and main optional in template configuration

CMakeLists.txt, test/CMakeLists.txt, test/cmake/chimeraTestBoostPython.cmake, test/cmake/chimeraTestPybind11.cmake
Currently, tests are included in `all` target when `BUILD_TESTING` is on. If we use (custom) target for building tests, we can build the tests without rerunning CMake with different options.
=> Make binding tests as a custom target

.ci/install_linux.sh, .ci/script.sh, .clang-format, CMakeLists.txt, cmake/ClangFormat.cmake, include/chimera/binding.h, include/chimera/configuration.h, include/chimera/frontend_action.h, include/chimera/mstch.h, include/chimera/util.h, include/chimera/visitor.h, src/chimera.cpp, src/configuration.cpp, src/consumer.cpp, src/frontend_action.cpp, src/mstch.cpp, src/util.cpp, src/visitor.cpp, tools/check_format.sh
**Changes**
* Add `.clang-format` with configuration settings that are similar to the current codebase
* Add two custom targets:
* `format`: format code
* `check-format`: check code and exit 0 on success
* Setup CI to check code formatting using `check-format` target
* Format the code
Resolves #177
=> Code formatting using ClangFormat 6.0

include/chimera/mstch.h, include/chimera/util.h, src/mstch.cpp, src/util.cpp, test/examples/02_class/class.h, test/examples/02_class/class.py, test/test_emulator.cpp
Skip generating a constructor if it contains a parameter of which type access is non-public.
This is a rework of #200 to resolve #178.
=> Skip constructors with non-public param types

test/examples/regression/issue228_template_type_alias/issue228_template_type_alias.py
This is necessary to build Chimera on PRL PPA. The pybind11 versions on Ubuntu package server (except Disco) are too old for Chimera.
=> Make pybind11 test optional

include/chimera/mstch.h
The definition of `CXXRecord::heldType()` was removed in [this commit](https://github.com/personalrobotics/chimera/commit/483674ffb300997950a4086a32becfbf5a57f7b7?w=1#diff-3f8c8328f0a509fbeb0a6d422bf8a85b) because "held_type" is simple text forwarding, which is supported by YAML. However, the declaration wasn't removed. This PR fixes it.
=> Remove undefined member function (CXXRecord::heldType())

external/mstch/include/mstch/mstch.hpp, include/chimera/mstch.h
This was originally introduced by https://github.com/personalrobotics/chimera/commit/ba8dd04203c75bdd8ef173c7033f5218acd56fff, but it's broken when merging the upstream in #132.
=> Fix inability to override methods

.azure-pipelines.yml, .ci/docker/Dockerfile.ubuntu-disco, .ci/docker/Dockerfile.ubuntu-eoan, .ci/docker/Dockerfile.ubuntu-focal, .ci/install_linux.sh, .ci/script.sh, .travis.yml, Brewfile, README.md
- Update CI images to recent OS versions
- Remove CI builds for deprecated OS versions
- Add CI builds for new OS versions
- Disable building tests for macOS (see: [#228](https://github.com/personalrobotics/chimera/issues/218)) and Ubuntu Focal (tests  fails for some reason)
- Install `yaml-cpp` without option `--with-static-lib` as it's removed
- Update `README.md` reflecting the updates
=> Update CI reflecting recent OS updates

.azure-pipelines.yml, cmake/chimeraFindLLVM.cmake, src/util.cpp
I wasn't able to find the root cause, but build with LLVM >= 7 causes segfault when the destructor of `clang::Parser` is called in `chimera::util::resolveDeclaration`.
This PR workaround by not destructing `clang::Parser` for LLVM >= 7. Since this workaround leads to a memory leak, this should be fixed once we figure out the root cause.
=> Workaround for segfault with LLVM >= 7

.ci/script.sh
It seems CI builds irregularly fail due to parallel build. I've been re-running every failed CI tests whenever they failed. Not sure if this is related to #212.
=> Disable parallel build on CI to avoid build failures

include/chimera/mstch.h, src/mstch.cpp, src/visitor.cpp, test/examples/regression/CMakeLists.txt, test/examples/regression/issue148_lambda_function/CMakeLists.txt, test/examples/regression/issue148_lambda_function/boost_python.yaml, test/examples/regression/issue148_lambda_function/issue148_lambda_function.cpp, test/examples/regression/issue148_lambda_function/issue148_lambda_function.h, test/examples/regression/issue148_lambda_function/issue148_lambda_function.py, test/examples/regression/issue148_lambda_function/pybind11.yaml
This PR suppresses #148 by skipping generating class binding that is being generated for lambda function defined in a header. We can safely skip the binding because the function contains the lambda function (i.e., `foo()` in the test) is still generated.
=> Suppress #148: Skip generating binding for lambda function

src/util.cpp, src/visitor.cpp, test/examples/regression/CMakeLists.txt, test/examples/regression/issue297_template_variable/CMakeLists.txt, test/examples/regression/issue297_template_variable/boost_python.yaml, test/examples/regression/issue297_template_variable/issue297_template_variable.cpp, test/examples/regression/issue297_template_variable/issue297_template_variable.h, test/examples/regression/issue297_template_variable/issue297_template_variable.py, test/examples/regression/issue297_template_variable/pybind11.yaml
The variable template is a C++14 feature. We need to (1) check which LLVM version added function `decl->getDescribedVarTemplate()` and (2) enable the test only when Chimera is built with C++14 supported compiler.
Fixes #297
=> Ignore unspecialized template variables

src/configuration.cpp
Otherwise, the warnings are regarded as the binding file name, which is an error.
=> Use std::cerr for warnings

.azure-pipelines.yml, .ci/install_macos.sh, .github/workflows/ccpp.yml, .travis.yml, README.md, cmake/chimeraFindLLVM.cmake, src/util.cpp, src/visitor.cpp
Drop supporting old LLVM versions. LLVM is available since Ubuntu 16.04, which is the oldest Ubuntu version that chimera currently supports.
=> Increase minimum required LLVM version to 6.0
